[package]
name = "cli"
edition = "2021"
authors.workspace = true
description.workspace = true
version.workspace = true
documentation.workspace = true

[dependencies]
jj-lib = { path = "../../jj/lib" }
jj-cli = { path = "../../jj/cli" }
async-trait.workspace = true
clap = "4.5.0"
